version: '3.7'

services:
  web:
    build: .
    image: collabright-web
    command: /app/docker/entrypoint.sh
    volumes:
      - .:/app/
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - mailhog
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=collabright
      - POSTGRES_PASSWORD=U9JA8BXh8MHbYRoUQGFeQL6X5MXemAStp2hZPPQU
      - POSTGRES_DB=collabrightdb
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
