# Generated by Django 3.2.4 on 2021-07-25 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210724_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='map_id',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='map_item',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='map_item_data',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.document'),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARC_GIS', 'Esri ArcGIS')], max_length=64)),
                ('data', models.TextField()),
                ('access_token', models.CharField(max_length=1024)),
                ('expiry_date', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=1024)),
                ('refresh_expiry_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
