# Generated by Django 3.2.4 on 2021-07-25 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210725_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='map_id',
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('map_url', models.CharField(max_length=512)),
                ('base_document_url', models.CharField(max_length=1024)),
                ('base_url', models.CharField(max_length=200)),
                ('map_id', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='audit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.audit'),
            preserve_default=False,
        ),
    ]
