# Generated by Django 3.2.4 on 2021-07-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210726_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='audit',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
