# Generated by Django 3.2.4 on 2021-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210726_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
