# Generated by Django 3.2.4 on 2021-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210726_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='map_print_definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
