# Generated by Django 3.2.4 on 2021-07-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_document_map_print_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='base_document_url',
        ),
    ]
