# Generated by Django 3.2.4 on 2021-07-28 19:38

import collabright.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_audit_base_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to=collabright.base.models.get_directory_path),
        ),
    ]
