# Generated by Django 3.2.4 on 2021-07-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
    ]
