# Generated by Django 3.2.4 on 2021-07-30 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_to_sign', models.BooleanField(default=False)),
                ('has_signed', models.BooleanField(default=False)),
                ('verdict', models.CharField(choices=[('APPROVED', 'Approved'), ('REQUESTED_CHANGES', 'Requested change')], max_length=64)),
                ('token', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=1024)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='base.audit')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.document')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
