# Generated by Django 3.2.4 on 2021-07-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contact'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='verdict',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REQUESTED_CHANGES', 'Requested change')], default='PENDING', max_length=64),
        ),
    ]
