# Generated by Django 3.2.4 on 2021-07-31 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210730_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=1024),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REVIEW', 'Review'), ('COMMENT', 'Comment')], default='REVIEW', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.audit')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reviewer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
