# Generated by Django 3.2.4 on 2021-07-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210731_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(),
        ),
    ]
