# Generated by Django 3.2.4 on 2021-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='envelop_id',
            field=models.UUIDField(null=True),
        ),
    ]
