# Generated by Django 3.2.4 on 2021-08-02 14:48

import collabright.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gis_base_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='token',
            field=models.CharField(default=collabright.base.models.make_token, max_length=1024),
        ),
    ]
