# Generated by Django 3.2.4 on 2021-08-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_audit_envelop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='envelop_id',
            new_name='envelope_id',
        ),
    ]
