# Generated by Django 3.2.4 on 2021-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_envelop_id_audit_envelope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='agrement',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
