# Generated by Django 3.2.4 on 2021-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_audit_agrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent')], default='created', max_length=64),
        ),
    ]
