# Generated by Django 3.2.4 on 2021-08-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210802_1448'),
        ('base', '0023_audit_status'),
    ]

    operations = [
    ]
