# Generated by Django 3.2.4 on 2021-08-04 12:42

import collabright.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_merge_0020_auto_20210802_1448_0023_audit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='agrement',
        ),
        migrations.AddField(
            model_name='audit',
            name='agreement',
            field=models.FileField(blank=True, upload_to=collabright.base.models.get_agreement_directory_path),
        ),
    ]
