# Generated by Django 3.2.4 on 2021-08-05 12:41

import collabright.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20210804_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to=collabright.base.models.get_agreement_directory_path),
        ),
    ]
