# Generated by Django 3.2.4 on 2021-08-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_audit_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
